[package]
name = "yt-mp3"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.11", features = ["derive"] }
rustube = "0.6.0"
rusty_ytdl = { version = "0.7.3", features = ["ffmpeg"] }
tokio = { version = "1.39.2", features = ["full"] }
